import { FC } from "react";
import Head from "next/head";
import styles from "../layouts/MainLayout.module.css";
import { NavBar } from "../NavBar";


type Props = {
  children: React.ReactNode
}

const Main: FC<Props> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>home</title>
        <meta name="description" content="Generated by PapuRobot" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className={styles.main}>{children}</main>
    </div>
  );
};

export default Main;
